stages:
  - test
  - build
  - deploy
test:
  stage: test
  script:
    - sh test.sh
build:
  stage: build
  script:
    - sh deploy.sh
  artifacts:
    paths:
    - dist/*
    expire_in: 5 weeks
deploy_devel:
  stage: deploy
  script:
  - rsync --recursive --progress dist/ gitlab-deploy@walrus.local.jemelik.eu:/var/www/html/
  environment:
    name: devel
  except:
  - canary
  - production
deploy_staging:
  stage: deploy
  script:
  - rsync --recursive --progress dist/ gitlab-deploy@coypu.local.jemelik.eu:/var/www/html/
  environment:
    name: staging
  only:
  - master
deploy_canary:
  stage: deploy
  script:
  - rsync --recursive --progress dist/ gitlab-deploy@riverrat.local.jemelik.eu:/var/www/html/
  environment:
    name: canary
  only:
  - canary
deploy_production:
  stage: deploy
  script:
  - rsync --recursive --progress dist/ /var/www/oyster-app/
  environment:
    name: production
  only:
  - production
